# Generated by Django 3.0.4 on 2020-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_type', models.CharField(choices=[('Bubble', 'Bubble'), ('Insertion', 'Insertion'), ('Merge', 'Merge')], default='Bubble', max_length=30)),
                ('input_array', models.FileField(upload_to='unsorted/')),
                ('sorted_array', models.FileField(blank=True, upload_to='sorted/')),
                ('execution_time', models.CharField(max_length=30)),
            ],
        ),
    ]
