version: "3.3"

services:
    pgdb:
        image: postgres:12.1
        container_name: sorting_app_pgdb
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
        ports:
            - 5432:5432
    web:
        build: ./
        container_name: sorting_app_web
        command: bash entrypoint.sh
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - pgdb

volumes:
    postgres_data: